### ISSUE TITLE
[Question] Why should I set action*2 if I want to get the correct output action in GAIL? 

### ISSUE THREAD

**Issue by LongchaoDa** [CherryPieSexy/imitation_learning#1]
Hi, Thank you for the implementation of the RL and IL algorithms, It is especially helpful! 
During realizing some of the models, I had a confusion on the size of output_action settings: 
For example, If I'm using GAIL, and for generator to output 2 (x,y)value, why should I set the real [ "out_put" *** 2** ] ?

Looking forward to your reply! Thank you!

**Comment by CherryPieSexy** [comment]
Hello!
When defining an actor (which is a neural net model) you should specify it's output size. For predicting actions you have to initialize a probability distribution by specifying it's parameters, for example for Normal distribution it is mu and sigma for each action coordinate. So, nn should produce parameters of double size compared to action dim.

It is true for every continuous distribution I've implemented.
For discrete distributions you should not double action dim.

**Comment by LongchaoDa** [comment]
It's so kind of you! Thanks for the answering and I saw the dim was truned to real out_put size (for example: in convert_params_beta() you used action_size = params_size//2)) And I got it now! Thanks again for the clear and extinguished work !

**Comment by LongchaoDa** [comment]
(Btw: Is it convenient for me to have your email? I'm trying to use GAIL with recurrent policy and I want to discuss more details about this, plus by email we could share screenshots I guess its more effective and I really admire your work so I would like to learn from you as a friend! (If you dont want too many to bother you, You may delete the email account comment after get my greeting email?))

**Comment by CherryPieSexy** [comment]
Glad to read that you managed to understand.
I have the email interga@post-hardcore.ru
And telegram CherryPieHSE
Feel free to reach me.

**Comment by LongchaoDa** [comment]
Thanks and My Telegram is: danielsmithda 
We may add each other both sides as mutual contacts to start a conversation!
