### ISSUE TITLE
Image and dict observation spaces support by BCO and GAIL implementations

### ISSUE THREAD

**Issue by akmandor** [CherryPieSexy/imitation_learning#2]
You mentioned in the README
> as: Behavioral Cloning from Observation (BCO) - technique to clone expert behavior into agent using only expert states, BCO (works bad for me, not supported now)

1. What do you mean by "works bad for me"? Does that specific to your experience OR Does the current BCO library (functions, data structures, etc) not fully functional?
2. Do the current BCO and GAIL support image and dict observation spaces?

**Comment by CherryPieSexy** [comment]
Hello!
1. It means both - during my initial experiments I was able to solve only CartPole environment using BCO, and after that I decided to focus on GAIL. I believe BCO code requires some modifications to run and now it is not fully functional.
2. GAIL supports image and dict observation spaces.

**Comment by CherryPieSexy** [comment]
@akmandor hello! Did I answer your question? Can I close the issue?

**Comment by akmandor** [comment]
Yeah, thanks for the answer!
